name: build-linux

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglfw3-dev

      - name: Configure CMake
        run: cmake -B ./build

      - name: Build
        run: cmake --build ./build --config Release
