name: static-analysis

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglfw3-dev cppcheck

      - name: Configure CMake
        run: cmake -B ./build -DFAIL_ON_WARNINGS=ON

      - name: Build
        run: cmake --build ./build
